const ActionTypes = {
    EDITOR: {
        CREATE: 'EDITOR.CREATE',
        DROP_NEW_MODEL: 'EDITOR.DROP_NEW_MODEL',
        ADD_NEW_MODEL: 'EDITOR.ADD_NEW_MODEL',
        ELEMENT_RIGHT_CLICKED: 'EDITOR.ELEMENT_RIGHT_CLICKED',
        ELEMENT_DOUBLE_CLICKED: 'EDITOR.ELEMENT_DOUBLE_CLICKED',
        ELEMENT_DELETE: 'EDITOR.ELEMENT_DELETE',
        ELEMENT_CANCEL: 'EDITOR.ELEMENT_CANCEL',
        ELEMENT_SAVE: 'EDITOR.ELEMENT_SAVE',
        ELEMENT_RESET:'EDITOR.ELEMENT_RESET',
        ELEMENT_LABEL_EDIT: 'EDITOR.ELEMENT_LABEL_EDIT',
        ELEMENT_LIKELIHOOD_EDIT: 'EDITOR.ELEMENT_LIKELIHOOD_EDIT',
        ELEMENT_LIKELIHOOD2_EDIT: 'EDITOR.ELEMENT_LIKELIHOOD2_EDIT',
        ELEMENT_LIKELIHOOD3_EDIT: 'EDITOR.ELEMENT_LIKELIHOOD3_EDIT',
        ELEMENT_CALCULATION_EDIT:'EDITOR.ELEMENT_CALCULATION_EDIT',
        ELEMENT_YEARS_EDIT:'EDITOR.ELEMENT_YEARS_EDIT',
        ELEMENT_CHANGE_X: 'EDITOR.ELEMENT_CHANGE_X',
        ELEMENT_CHANGE_Y: 'EDITOR.ELEMENT_CHANGE_Y',
        ELEMENT_CHANGE_TYPE: 'EDITOR.ELEMENT_CHANGE_TYPE',
        ELEMENT_CHANGE_RELATION: 'EDITOR.ELEMENT_CHANGE_RELATION',        
        TOOL_ELEMENT_CLICKED: 'EDITOR.TOOL_ELEMENT_CLICKED',
        TOOL_ELEMENT_RELEASED: 'EDITOR.TOOL_ELEMENT_RELEASED',
        TOOL_TAB_SELECTED: 'EDITOR.TOOL_TAB_SELECTED',
        MENU_CLEAR_CLICKED: 'EDITOR.MENU_CLEAR_CLICKED',
        MENU_CLEAR_CONFIRMED: 'EDITOR.MENU_CLEAR_CONFIRMED',
        CELL_CLICKED: 'EDITOR.CELL_CLICKED',
        CELL_HANDLE_CLICKED: 'EDITOR.CELL_HANDLE_CLICKED',
        CELL_HANDLE_RELEASED: 'EDITOR.CELL_HANDLE_RELEASED',
        CELL_HANDLE_MOVED: 'EDITOR.CELL_HANDLE_MOVED'
    }
}

export default ActionTypes;
